-- This script helps create an admin user
-- The UUID (id) is auto-generated by default

-- First, ensure the id column has a default value
ALTER TABLE public.admin_users 
ALTER COLUMN id SET DEFAULT gen_random_uuid();

-- To create an admin, you need to:
-- 1. Create a user in Supabase Auth (via signup or dashboard)
-- 2. Then link them to admin_users with this query:

-- Example: After a user signs up with email 'admin@example.com', 
-- find their auth.users id and run:
/*
INSERT INTO public.admin_users (auth_user_id, email, name, role)
SELECT 
  id as auth_user_id,
  email,
  'Admin Name' as name,
  'admin' as role
FROM auth.users
WHERE email = 'admin@example.com';
*/

-- Or if you know the auth user id directly:
/*
INSERT INTO public.admin_users (auth_user_id, email, name, role)
VALUES (
  'your-auth-user-uuid-here',
  'admin@example.com',
  'Admin Name',
  'admin'
);
*/
